language: node_js
node_js:
  - 8
install:
  - npm install
script:
  - NODE_ENV=production ./node_modules/.bin/ng build
deploy:
  on:
    branch: master
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
